[*]
# Format-specific settings appear
# under a user-provided "glob"
# pattern.

StylesPath = styles
MinAlertLevel = suggestion

Vocab = Vale

Packages = Readability

[*.md]
BasedOnStyles = Vale, Readability

Vale.Terms = NO
